### ISSUE TITLE
关于配置文件的编写

### ISSUE THREAD

**Issue by zyt20001205** [exzhawk/wailanbt#42]
例如IC2exp mod中的高级采矿机属性中有一个“模式”标签 以0代表非精准采集 1代表精准采集 但是直接在配置文件中编写“mode”:Mode只能显示0或1 请问怎么能在代码中直接显示 非精准采集/精准采集 而不是0或1

**Comment by exzhawk** [comment]
Use Omni Ocular and learn JavaScript

**Comment by zyt20001205** [comment]
也就是说这个mod无法实现吗

**Comment by exzhawk** [comment]
Using this mod is not recommanded by any means.
Omni Ocular is the successor of WailaNBT, with major code rewrite and much more feature. I strongly suggest that you try it out at https://minecraft.curseforge.com/projects/omni-ocular or https://github.com/exzhawk/OmniOcular

**Comment by zyt20001205** [comment]
谢谢作者的推荐 omniocular确实能够解决我的问题 我相比较只是觉得wailanbt配置文件的编写更加适合我这样的新手

**Comment by zyt20001205** [comment]
omniocular游戏内重载config文件的指令是/oor吗

**Comment by exzhawk** [comment]
Do not post unrelated content here. RTFM
